FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY Kafka-PySpark/twitter_validation.csv ./
COPY Kafka-PySpark/producer-validation-tweets-docker.py ./producer-validation-tweets.py

# Wait for Kafka to be ready
CMD python producer-validation-tweets.py
